import React from 'react';
import { Link } from 'react-router-dom';
import PageLayout from '@/components/askjds/PageLayout';

export function Disclaimer() {
  return (
    <PageLayout>
      <div className="min-h-screen bg-white">
        <div className="max-w-4xl mx-auto px-4 py-16">
          <div className="text-center mb-12">
            <h1 className="text-4xl font-bold text-gray-900 mb-4">Disclaimer</h1>
            <p className="text-lg text-gray-600">Important Legal Notices and Limitations</p>
          </div>

          <div className="prose prose-lg max-w-none text-gray-800">
            <div className="bg-red-50 border-l-4 border-red-500 p-6 mb-8">
              <p className="text-red-800 font-medium">
                <strong>IMPORTANT:</strong> Please read this disclaimer carefully. Your use of Ask JDS and JD Simplified services indicates your acceptance of these disclaimers and limitations.
              </p>
            </div>

            <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">Educational Content Only</h2>
            <p>The information, content, and materials provided through Ask JDS and JD Simplified are intended solely for educational and informational purposes related to law school study and bar exam preparation. This includes but is not limited to:</p>
            <ul>
              <li>AI-generated explanations of legal concepts</li>
              <li>Study materials, flashcards, and outlines</li>
              <li>Video lectures and training content</li>
              <li>Practice questions and answers</li>
              <li>Legal analysis and case summaries</li>
            </ul>

            <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">Not Legal Advice</h2>
            <div className="bg-amber-50 border-l-4 border-amber-500 p-6 mb-6">
              <p className="text-amber-800 font-medium">
                <strong>No Legal Advice:</strong> Nothing on this platform constitutes legal advice, and no attorney-client relationship is created between you and JD Simplified, its owners, operators, or contributors.
              </p>
            </div>

            <p>Our service is designed to help you learn and understand legal concepts for academic purposes. It is NOT intended to:</p>
            <ul>
              <li>Provide legal advice for real-world situations</li>
              <li>Replace consultation with a qualified attorney</li>
              <li>Be used in actual legal proceedings or practice</li>
              <li>Serve as a substitute for professional legal representation</li>
              <li>Guide actual legal decision-making</li>
            </ul>

            <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">AI-Generated Content Limitations</h2>
            <p>A significant portion of our content is generated by artificial intelligence systems. While we strive to provide accurate and helpful information, you should be aware of these important limitations:</p>

            <h3 className="text-xl font-semibold text-gray-900 mt-6 mb-3">Accuracy Disclaimer</h3>
            <ul>
              <li><strong>No Guarantee of Accuracy:</strong> AI-generated content may contain errors, inaccuracies, or outdated information</li>
              <li><strong>Not Always Current:</strong> Legal information may not reflect the most recent changes in law, regulations, or judicial decisions</li>
              <li><strong>Contextual Limitations:</strong> AI may not fully understand the nuances of complex legal scenarios</li>
              <li><strong>Oversimplification Risk:</strong> Complex legal concepts may be oversimplified in AI explanations</li>
            </ul>

            <h3 className="text-xl font-semibold text-gray-900 mt-6 mb-3">Your Responsibility</h3>
            <p>When using AI-generated content, you should:</p>
            <ul>
              <li>Cross-reference information with authoritative legal sources</li>
              <li>Verify citations and case references independently</li>
              <li>Consult your textbooks, casebooks, and class materials</li>
              <li>Seek clarification from professors or instructors when needed</li>
              <li>Use the content as a starting point for further study, not as a final authority</li>
            </ul>

            <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">Exam Performance and Results</h2>
            <p><strong>No Guarantees:</strong> We make no representations, warranties, or guarantees regarding:</p>
            <ul>
              <li>Your performance on law school exams</li>
              <li>Your success on the bar examination</li>
              <li>Your academic grades or class rank</li>
              <li>Your admission to the bar or any licensing process</li>
              <li>Your career prospects or job placement</li>
            </ul>

            <p>Success in law school and on the bar exam depends on numerous factors including but not limited to your individual effort, study habits, test-taking ability, and comprehension of the material beyond what our platform provides.</p>

            <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">Jurisdictional Limitations</h2>
            <p>Our content is primarily focused on United States federal law and general legal principles commonly taught in American law schools. Please note:</p>
            <ul>
              <li><strong>State Law Variations:</strong> State laws may differ significantly from federal law and from each other</li>
              <li><strong>International Users:</strong> Content may not be applicable to legal systems outside the United States</li>
              <li><strong>Local Practice:</strong> Local court rules and procedures may vary from general principles discussed</li>
              <li><strong>Specialized Areas:</strong> Some highly specialized areas of law may not be comprehensively covered</li>
            </ul>

            <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">Academic Integrity</h2>
            <p>You are responsible for using our service in compliance with your institution's academic integrity policies. This includes:</p>
            <ul>
              <li><strong>No Cheating:</strong> Do not use our service to complete assignments that are meant to be your own original work</li>
              <li><strong>Proper Attribution:</strong> If your institution requires citation of study aids, include appropriate references</li>
              <li><strong>Exam Restrictions:</strong> Do not access our service during closed-book exams or when prohibited</li>
              <li><strong>Honor Code Compliance:</strong> Ensure your use complies with your school's honor code and academic policies</li>
            </ul>

            <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">Technology and Service Limitations</h2>
            <p>Our service is provided "as is" and "as available." We disclaim all warranties regarding:</p>
            <ul>
              <li>Uninterrupted service availability</li>
              <li>Error-free operation</li>
              <li>Freedom from viruses or harmful components</li>
              <li>Compatibility with all devices or browsers</li>
              <li>Data backup and recovery</li>
            </ul>

            <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">Third-Party Content</h2>
            <p>Our platform may contain links to or references to third-party websites, materials, or resources. We do not:</p>
            <ul>
              <li>Endorse or approve third-party content</li>
              <li>Control the accuracy of external websites</li>
              <li>Assume responsibility for third-party materials</li>
              <li>Warrant the reliability of external links</li>
            </ul>

            <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">Changes and Updates</h2>
            <p>Legal information, regulations, and judicial decisions change frequently. We may not immediately update our content to reflect these changes. Always verify the current state of the law through official sources before relying on any legal information.</p>

            <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">Limitation of Liability</h2>
            <p>To the fullest extent permitted by law, JD Simplified and its affiliates, owners, employees, and agents shall not be liable for any damages arising from:</p>
            <ul>
              <li>Reliance on information provided through our service</li>
              <li>Errors, inaccuracies, or omissions in our content</li>
              <li>Service interruptions or technical failures</li>
              <li>Academic or professional consequences of using our platform</li>
              <li>Decisions made based on our educational materials</li>
            </ul>

            <div className="bg-blue-50 border-l-4 border-blue-500 p-6 mt-8">
              <h3 className="text-lg font-semibold text-blue-900 mb-2">Questions About This Disclaimer?</h3>
              <p className="text-blue-800">
                If you have questions about this disclaimer or our service limitations, please review our <Link to="/terms" className="text-blue-600 hover:underline">Terms of Service</Link> and <Link to="/privacy" className="text-blue-600 hover:underline">Privacy Policy</Link>, or contact us at support@jdsimplified.com.
              </p>
            </div>

            <div className="bg-gray-50 p-6 rounded-lg mt-8">
              <p><strong>Contact Information:</strong></p>
              <p>JD Simplified, LLC<br />
              7901 4TH ST N STE 300<br />
              ST PETERSBURG, FL 33702<br />
              Email: support@jdsimplified.com</p>
            </div>

            <p className="mt-8 text-sm text-gray-600">
              This disclaimer was last updated on May 11, 2025. We may update this disclaimer from time to time, and your continued use of our service constitutes acceptance of any changes.
            </p>
          </div>
        </div>
      </div>
    </PageLayout>
  );
} 