name: Deploy Ask JDS & JD Simplified

on:
  push:
    branches:
      - main

jobs:
  deploy-askjds:
    name: Deploy Ask JDS
    runs-on: ubuntu-latest
    # Allow concurrent execution but cancel if new push arrives
    concurrency: 
      group: deploy-askjds-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout Code
        # Pinned SHA for security and stability
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      
      - name: Setup Node
        # Pinned SHA for security and stability
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3.8.2
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
        continue-on-error: true
      
      - name: Install Dependencies (Optimized)
        run: |
          # Use npm ci with optimized flags for faster installs
          npm ci --legacy-peer-deps --prefer-offline --no-audit --no-fund

      - name: Fix known security vulnerabilities
        run: npm audit fix --legacy-peer-deps || true

      - name: Build Ask JDS
        env:
          VITE_SUPABASE_URL_PROD: ${{ secrets.VITE_SUPABASE_URL_PROD }}
          VITE_SUPABASE_ANON_KEY_PROD: ${{ secrets.VITE_SUPABASE_ANON_KEY_PROD }}
          VITE_SUPABASE_URL_DEV: ${{ secrets.VITE_SUPABASE_URL_DEV }}
          VITE_SUPABASE_ANON_KEY_DEV: ${{ secrets.VITE_SUPABASE_ANON_KEY_DEV }}
          # Legacy variables for backward compatibility
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL_DEV }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY_DEV }}
          # Video hosting
          VITE_GUMLET_ACCOUNT_ID: ${{ secrets.VITE_GUMLET_ACCOUNT_ID }}
          # Image optimization
          VITE_TWICPICS_DOMAIN: ${{ secrets.VITE_TWICPICS_DOMAIN }}
          # Video analytics
          VITE_GUMLET_PROPERTY_ID: ${{ secrets.VITE_GUMLET_PROPERTY_ID }}
        run: npx vite build --mode askjds

      - name: Copy build artifacts to proper directory
        run: |
          mkdir -p dist_askjds
          cp -r dist/* dist_askjds/

      - name: Verify build output
        run: |
          if [ ! -f dist_askjds/index.html ]; then
            echo "Error: Build output missing index.html file"
            exit 1
          fi
          echo "Build verification successful"

      - name: Deploy to S3
        # Pinned SHA for security and stability
        uses: jakejarvis/s3-sync-action@be0c4ab89158cac4278689ebedd8407dd5f35a83 # v0.5.1
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: ask-jds
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: dist_askjds

      - name: Invalidate CloudFront
        # Pinned SHA for security and stability
        uses: koki-develop/cloudfront-invalidate-action@7d446a985457fcb851f68f153cb762887633d1df # v1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        with:
          id: ${{ secrets.CLOUDFRONT_ID_ASKJDS }}
          paths: "/*"

  deploy-jdsimplified:
    name: Deploy JD Simplified
    runs-on: ubuntu-latest
    # Allow concurrent execution but cancel if new push arrives
    concurrency: 
      group: deploy-jdsimplified-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout Code
        # Pinned SHA for security and stability
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      
      - name: Setup Node
        # Pinned SHA for security and stability
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3.8.2
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
        continue-on-error: true
      
      - name: Install Dependencies (Optimized)
        run: |
          # Use npm ci with optimized flags for faster installs
          npm ci --legacy-peer-deps --prefer-offline --no-audit --no-fund

      - name: Fix known security vulnerabilities
        run: npm audit fix --legacy-peer-deps || true

      - name: Build JD Simplified
        env:
          VITE_SUPABASE_URL_PROD: ${{ secrets.VITE_SUPABASE_URL_PROD }}
          VITE_SUPABASE_ANON_KEY_PROD: ${{ secrets.VITE_SUPABASE_ANON_KEY_PROD }}
          VITE_SUPABASE_URL_DEV: ${{ secrets.VITE_SUPABASE_URL_DEV }}
          VITE_SUPABASE_ANON_KEY_DEV: ${{ secrets.VITE_SUPABASE_ANON_KEY_DEV }}
          # Legacy variables for backward compatibility
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL_DEV }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY_DEV }}
          # Video hosting
          VITE_GUMLET_ACCOUNT_ID: ${{ secrets.VITE_GUMLET_ACCOUNT_ID }}
          # Image optimization
          VITE_TWICPICS_DOMAIN: ${{ secrets.VITE_TWICPICS_DOMAIN }}
          # Video analytics
          VITE_GUMLET_PROPERTY_ID: ${{ secrets.VITE_GUMLET_PROPERTY_ID }}
        run: npx vite build --mode jds

      - name: Copy build artifacts to proper directory
        run: |
          mkdir -p dist_jdsimplified
          cp -r dist/* dist_jdsimplified/

      - name: Verify build output
        run: |
          if [ ! -f dist_jdsimplified/index.html ]; then
            echo "Error: Build output missing index.html file"
            exit 1
          fi
          echo "Build verification successful"

      - name: Deploy to S3
        # Pinned SHA for security and stability
        uses: jakejarvis/s3-sync-action@be0c4ab89158cac4278689ebedd8407dd5f35a83 # v0.5.1
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: jdsimplified
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: dist_jdsimplified

      - name: Invalidate CloudFront
        # Pinned SHA for security and stability
        uses: koki-develop/cloudfront-invalidate-action@7d446a985457fcb851f68f153cb762887633d1df # v1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        with:
          id: ${{ secrets.CLOUDFRONT_ID_JDS }}
          paths: "/*"

  deploy-admin:
    name: Deploy Admin Panel
    runs-on: ubuntu-latest
    # Allow concurrent execution but cancel if new push arrives
    concurrency: 
      group: deploy-admin-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout Code
        # Pinned SHA for security and stability
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      
      - name: Setup Node
        # Pinned SHA for security and stability
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3.8.2
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
        continue-on-error: true
      
      - name: Install Dependencies (Optimized)
        run: |
          # Use npm ci with optimized flags for faster installs
          npm ci --legacy-peer-deps --prefer-offline --no-audit --no-fund

      - name: Fix known security vulnerabilities
        run: npm audit fix --legacy-peer-deps || true

      - name: Build Admin Panel
        env:
          VITE_SUPABASE_URL_PROD: ${{ secrets.VITE_SUPABASE_URL_PROD }}
          VITE_SUPABASE_ANON_KEY_PROD: ${{ secrets.VITE_SUPABASE_ANON_KEY_PROD }}
          VITE_SUPABASE_URL_DEV: ${{ secrets.VITE_SUPABASE_URL_DEV }}
          VITE_SUPABASE_ANON_KEY_DEV: ${{ secrets.VITE_SUPABASE_ANON_KEY_DEV }}
          # Legacy variables for backward compatibility
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL_DEV }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY_DEV }}
          # Video hosting
          VITE_GUMLET_ACCOUNT_ID: ${{ secrets.VITE_GUMLET_ACCOUNT_ID }}
          # Image optimization
          VITE_TWICPICS_DOMAIN: ${{ secrets.VITE_TWICPICS_DOMAIN }}
          # Video analytics
          VITE_GUMLET_PROPERTY_ID: ${{ secrets.VITE_GUMLET_PROPERTY_ID }}
        run: npx vite build --mode admin

      - name: Copy build artifacts to proper directory
        run: |
          mkdir -p dist_admin
          cp -r dist/* dist_admin/

      - name: Verify build output
        run: |
          if [ ! -f dist_admin/index.html ]; then
            echo "Error: Build output missing index.html file"
            exit 1
          fi
          echo "Build verification successful"

      - name: Deploy to S3
        # Pinned SHA for security and stability
        uses: jakejarvis/s3-sync-action@be0c4ab89158cac4278689ebedd8407dd5f35a83 # v0.5.1
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: jds-admin
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: dist_admin

      - name: Invalidate CloudFront
        # Pinned SHA for security and stability
        uses: koki-develop/cloudfront-invalidate-action@7d446a985457fcb851f68f153cb762887633d1df # v1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        with:
          id: ${{ secrets.CLOUDFRONT_ID_ADMIN }}
          paths: "/*"