name: Deploy to S3 & CloudFront

on:
  push:
    branches:
      - main  # Runs on push to main

jobs:
  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
        run: npm run build  # Ensure your build script uses VITE_ prefixed variables

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --delete  # Removes old files from S3
        env:
          AWS_S3_BUCKET: ${{ secrets.S3_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: "dist"  # Ensure this matches your React output directory

      # New step: Invalidate CloudFront cache
      - name: Invalidate CloudFront Cache
        uses: koki-develop/cloudfront-invalidate-action@v1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        with:
          id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          # 'paths' input is optional; defaults to '/*' to clear all files [oai_citation_attribution:5‡github.com](https://github.com/koki-develop/cloudfront-invalidate-action#:~:text=Name%20Description%20,The%20default%20is)
