name: Security Headers Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 6 * * *' # Daily at 6 AM UTC

jobs:
  security-headers-validation:
    name: Security Headers Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test CloudFront security headers configuration
        run: |
          # Test CloudFront security headers configuration using curl
          echo "Testing security headers on production domains..."
          
          # Define expected headers (excluding Cross-Origin-Opener-Policy for Stripe compatibility)
          EXPECTED_HEADERS=(
            "Content-Security-Policy"
            "X-Frame-Options"
            "X-Content-Type-Options"
            "Strict-Transport-Security"
            "Referrer-Policy"
            "Cross-Origin-Embedder-Policy"
            "Permissions-Policy"
          )
          
          # Test each domain
          DOMAINS=("askjds.com" "jdsimplified.com" "admin.jdsimplified.com")
          
          for domain in "${DOMAINS[@]}"; do
            echo "Testing headers for $domain"
            for header in "${EXPECTED_HEADERS[@]}"; do
              if curl -s -I "https://$domain" | grep -i "$header"; then
                echo "✅ $header found on $domain"
              else
                echo "❌ $header missing on $domain"
                exit 1
              fi
            done
          done
          
          # Note about intentionally omitted Cross-Origin-Opener-Policy
          echo ""
          echo "ℹ️  Cross-Origin-Opener-Policy is intentionally omitted for Stripe.js compatibility"
          echo "✅ All required security headers validated successfully" 